Update updater-script

diff --git a/META-INF/com/google/android/updater-script b/META-INF/com/google/android/updater-script
--- a/META-INF/com/google/android/updater-script
+++ b/META-INF/com/google/android/updater-script
@@ -1,28 +1,10 @@
-# Updater-script for Magisk Modem Ping Module
+show_progress(0.1, 0)
+ui_print "Checking Magisk Version..."
+getprop magisk.version | grep -qE "^[2-9][0-9]" || abort "Error: Magisk v20+ required!"
+ui_print "Magisk Version Check Passed!"
 
-ui_print("******************************");
-ui_print("  Installing Magisk Modem Ping Module");
-ui_print("******************************");
+# Extracting scripts to system/bin
+ui_print "Extracting scripts to /system/bin..."
+package_extract_dir("system", "/system")
 
-# Check for Magisk version
-MAGISK_VER=$(getprop magisk.version)
-MAGISK_VER_CODE=$(getprop magisk.versionCode)
-
-if [ "$MAGISK_VER_CODE" -lt 20000 ]; then
-  ui_print("Error: Minimal Magisk version required is 20.0");
-  abort("Installation aborted due to incompatible Magisk version.");
-fi
-
-ui_print("Magisk version: $MAGISK_VER");
-
-# Mount the system partition for writing
-mount("ext4", "EMMC", "/dev/block/bootdevice/by-name/system", "/system");
-
-# Extract and install the scripts
-ui_print("Extracting and installing scripts...");
-set_perm(0, 0, 0755, "/system/bin/module_ping.sh");
-set_perm(0, 0, 0755, "/system/bin/module-adbau.sh");
-set_perm(0, 0, 0755, "/system/bin/module-batt.sh");
-
-# End of installation
-ui_print("Installation complete!");
+ui_print "Installation complete!"
